# Generated by Django 4.2.20 on 2025-06-07 05:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0011_alter_reporte_uso_material_fecha'),
    ]

    operations = [
        migrations.AlterField(
            model_name='producto',
            name='nombre',
            field=models.CharField(choices=[('aguja_americana_15', 'Aguja Americana 15'), ('aguja_americana_14', 'Aguja Americana 14'), ('aguja_americana_16', 'Aguja Americana 16'), ('aguja_vastago_rl', 'Aguja Vastago RL'), ('aguja_vastago_rs', 'Aguja Vastago RS'), ('aguja_vastago_rm', 'Aguja Vastago RM'), ('labret', 'Labret'), ('septum', 'Septum'), ('barbell', 'Barbell'), ('nostril', 'Nostril'), ('aro', 'Aro'), ('tinta_negra_oz', 'Tinta Negra Oz'), ('tinta_blanca_oz', 'Tinta Blanca Oz'), ('rollo_papel_sanitario', 'Rollo Papel Sanitario'), ('paquete_toallitas_humedas', 'Paquete Toallitas Humedas')], max_length=50),
        ),
        migrations.AlterField(
            model_name='producto',
            name='precio',
            field=models.IntegerField(default=250),
        ),
        migrations.AlterField(
            model_name='reporte_uso_material',
            name='fecha',
            field=models.DateField(default=datetime.date(2025, 6, 6)),
        ),
        migrations.AlterField(
            model_name='tattoo',
            name='precio',
            field=models.IntegerField(default=250, max_length=10000),
        ),
    ]
