# Generated by Django 4.2.20 on 2025-06-07 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0012_alter_producto_nombre_alter_producto_precio_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reporte_abastecimiento',
            name='costoTot',
            field=models.DecimalField(blank=True, decimal_places=2, default=1.0, max_digits=15, null=True),
        ),
    ]
